project:
  type: book
  output-dir: docs

book:
  title: "Workshop Bash & R"
  author: 
    - Emilio Ortiz-Avila
    - Mayela Fosado-Mendoza
    - Mariana Devon
  date: "11/18/2025"
  page-navigation: true
  chapters:
    - index.qmd
    - req_B.qmd
    - req_R.qmd
    - Bpracticas.qmd
    - intro_bash.qmd
    - intro_R.qmd
    - Cap1_B.qmd
    - Cap1_R.qmd
    - Cap2_B.qmd
    - Cap3_B.qmd
    - Cap4_B.qmd
    - Cap5_B.qmd
  # Information
  repo-url: https://github.com/ISCB-RSG-MEXICO/Workshop_template # link de Github
  sharing: [twitter, facebook, linkedin]
  favicon: "rsgMexico.jpeg" # icono de la pagina en pestana


format:
  html:
    toc-depth: 4
    number-depth: 3
  # Boton para cambiar tema de oscuro a claro
    theme:
      light: minty
      dark: darkly
    code-fold: show # Ocultar codigo
    code-copy: true # Copy button
    freeze: false  # Desactivar congelamiento

editor: visual

